version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - docker-compose build


  build:
    commands:
      - echo Entered the build phase
      - docker-compose run --rm test
      - docker-compose stop
      - docker-compose rm -vf
      - docker-compose run --rm -w /go/src/github.com/quorumcontrol/inhouse integration bin/_integration.sh
      - bin/release.sh